### ISSUE TITLE
Design values

### ISSUE THREAD

**Issue by rugk** [rugk/streetcomplete-website#5]
I'll start to collect some design values (actually already started in the main issue):
* **Playfull:** StreetComplete is gamified, we want to reflect that, but make a serious website anyway. Playfullness can be hidden in details, etc.
* **Interactive:** The website is technically static, but should not feel like that. We may embed maps, add quest markers. etc.
* **Non-technical:** Our target audience are users, who have no idea of StreetComplete, OSM, and so on.
   We will not try to convince them of OSM. We may not even mention OSM, but I guess we should do this, at least somewhere near the bottom.
* **Non-standard:** The website should not have these usual straight lines, cuts based on height or so. It is a project website, but – combined with stuff above – it should be kept in mind, and not look as any other website.

## Technical

* **Best goes first:** Of course, the best arguments/interactive stuff should be presented first. At the bottom, we can present 
* **Prototype early:** I know it's hard to resist, but let's focus on details later. If e.g. our map markers look bad, we rather want to have them anyway, first.
* **Try out:** We may revise the design at any time.
* **Use new stuff:** Websites will anyway get older over time, so we rather use the new stuff.
* **Less JS**: We may not need it, or CSS is better.

## So?

Any other important points? All agreeable?

**Comment by ENT8R** [comment]
I totally agree with all of your points! Sounds like this is going to be an awesome website 😄

**Comment by rugk** [comment]
There is nothing to add, but keep them in mind… :smile:
