### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by rugk** [rugk/streetcomplete-website#6]
Let's list the content we want to include (mostly taken from original issue https://github.com/westnordost/StreetComplete/issues/1130):
* header image of StreetComplete
* some example quests
* Screenshots of real app/animations
* points why StreetComplete is fun/amazing/helps the world
* why StreetComplete is easy to use?
* download buttons somewhere (maybe even fixed?)
* links to more resources: contributing information
  * GitHub link
  * contributing information -> link to Contributing.md of SC
  * [quest list](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) (should this be a small note, or rather something more big at the top linked like "See all our available quests"?)

## Things I am not sure about

* Do we want these "Quotes" from users? Marketing-like I'd like it. Don't know though whether we have so much.
* Somehow embed ratings from Google Play? Or at least not embed, but somehow "copy paste" :wink:

**Comment by ENT8R** [comment]
> some example quests

Something like a small map with the same style that StreetComplete uses and then some markers on the map and showing some quests like it would be done in the app? That would be nice IMO...

> Do we want these "Quotes" from users? Marketing-like I'd like it. Don't know though whether we have so much.

There are actually some on Google Play, but they are nearly all saying the same 😄: that StreetComplete is a great app to add small details to OSM while walking/doing nothing...

> Somehow embed ratings from Google Play?

I would not embed them, maybe we then show some (unwanted) "bad" ratings which is bad for our marketing...

**Comment by rugk** [comment]
> Something like a small map with the same style that StreetComplete uses and then some markers on the map and showing some quests like it would be done in the app?

Yep, exactly. More or less interactive one.

**Comment by rugk** [comment]
Okay, as for ratings we need to select good ones, okay.😊

**Comment by rugk** [comment]
Finished
